######
# APIs:
#   - provision
#   - bind
#   - verify
#   - unbind
#   - deprovision
######
# Example multi-apb integration test
provision: ansibleplaybookbundle/mediawiki-apb
provision: ansibleplaybookbundle/postgresql-apb

bind: ansibleplaybookbundle/postgresql-apb
verify: rthallisey/service-broker-ci/verify-mediawiki-postgresql.sh
unbind: postgresql-apb | mediawiki-apb

deprovision: ansibleplaybookbundle/mediawiki-apb
deprovision: ansibleplaybookbundle/postgresql-apb

######
# How to use the API calls:
#
#  - A Template with the name 'mediawiki123-apb' is expected at the address:
#    'https://github.com/ansibleplaybookbundle/mediawiki-apb/blob/master/templates/mediawiki-apb.yaml'
#
#       provision: ansibleplaybookbundle/mediawiki-apb
#
#  - To reference a local template in './templates/postgresql.yaml', use this
#    format.
#
#       provision: postgresql
#
#  - Specify the path of the BindApp. This will bind to the first provisioned
#    app that is not the same as the BindApp.
#  - This will look for the file './templates/postgresql-mediawiki-apb-bind.yaml'
#    and bind postgresql to mediawiki.
#
#        provision: ansibleplaybookbundle/mediawiki-apb
#        bind: postgresql
#
#  - Verify any action has succeeded.
#  - The verify field is run as a shell command
#
#        verify: kubectl get pods | grep Running | grep mediawiki123
#        verify: verify-app-health.sh
#
#  - The BindApp is the application that is binded to the BindTarget.
#  - Format:
#      <BindApp> | <BindTarget>
#  - Unbind postgresql from mediawiki.
#
#        unbind: postgresql | mediawiki123-apb
#
######
